= DISCUSSION AND LIMITATIONS <sec:discussion_limitations>

== Discussion
The results of the simulated system design indicate that the approach of separating the operational layers between the Smart Meter Simulator, Backend Service, and Solana Smart Contract enables the Peer-to-Peer energy trading system to have a verifiable structure with clearer points for system expansion. The Backend Service acts as the primary control layer for validating data, managing permissions, and evaluating grid-stability conditions before submitting transactions to the blockchain, so that the Smart Contract does not have to bear the entire processing burden of the microgrid system.

Using the Solana Smart Contract as a Settlement and Audit layer enhances the transparency of energy transactions, because trade orders and energy settlement states can be audited retrospectively. However, the system must still prioritize the safety of the electrical grid first. Therefore, transaction approval should not consider only the price and energy quantity, but must also take into account system stability conditions and the connection status of the devices.

The three-part evaluation supports the design hypothesis that the blockchain serves as a thin settlement layer. First, the ingest path keeps the loss ratio close to zero (≤ 0.03%) up to a load of 640 devices (see @sec:ingest-saturation), where the measured ingest rate is a lower bound of a single sender client and does not increase monotonically with the number of meters, so no conclusion is drawn about the service saturation point; this indicates that moving the high-frequency validation and aggregation work to the off-chain layer does not become a system bottleneck under the tested load levels. Second, the measured on-chain settlement cost of 96,707 CU per order pair accounts for approximately 48% of the initial per-instruction compute budget (see @sec:settlement-cost), showing that once most business rules are enforced off-chain, the remaining on-chain burden is at a level that opens a compute-wise opening to combine multiple order pairs into a single transaction (batch settlement), although the actual combination is constrained by the transaction packet size before the compute ceiling (see @sec:tx-structure), so the signature-packing method must be adjusted to actually reduce the per-order-pair cost in future work. Third, the fact that the on-chain cost is a deterministic CU value rather than varying with public-network market fees is consistent with the governance rationale for choosing a PoA consortium network (see @sec:related-work), where transaction costs are predictable and independent of gas volatility.

In terms of economic mechanism, separating the roles of the three token types — the energy token certified by REC for delivery, the THBC coin pegged to the baht for pricing and payment, and the GRX token for stake and governance — enables transaction settlement to be DvP, which binds energy delivery to payment in a single transaction, and grants network governance rights under a consortium framework that clearly controls REC certification and the aggregator allow-list. We have analyzed the preliminary model-derived economic implications of the net amount received by sellers and the premium relative to the feed-in tariff in @sec:revenue-sensitivity. However, the full measurement of economic properties, such as allocative efficiency / welfare and the strategic behavior of participants, remains outside the scope of the architectural evaluation in this work.

Compared with permissioned platforms widely used in the P2P energy trading literature such as Hyperledger Fabric @androulaki2018hyperledger (see @tbl:comparison), the design in this work differs architecturally in three points. First, Fabric uses an execute-order-validate processing model in which chaincode runs on endorsing peers before ordering through an orderer (Raft/BFT), whereas this work uses Solana's account model that processes transactions in parallel via Sealevel when the sets of written accounts do not overlap (see @sec:sealevel-sharding), which facilitates scaling order submission per entity but makes settlements that reconcile a central balance bound to a central write (global-write-bound), as measured in @sec:onchain-throughput. Second, the processing cost in this work is expressed in compute units (CU) that are deterministic and have a clear per-transaction ceiling, unlike Fabric, which has no equivalent concept of a per-transaction compute budget, making this work's on-chain cost straightforward to predict and to detect regression. Third, this work enforces the provenance check of meter readings with Ed25519 signatures and replay prevention through an order nullifier directly within the program logic, instead of relying on an external endorsement policy. This comparison is qualitative (architectural) because there is not yet a head-to-head measurement on the same energy workload, which is a quantitative comparison left open for the future.

== Limitations
A key limitation of this work is that the system is still at the simulation level, with energy data coming from the Smart Meter Simulator and not yet tested together with real Smart Meter devices or field electrical systems. Therefore, the results reflect the suitability of the architecture and the preliminary working process rather than quantitative performance in a real environment.

In addition, the evaluation covers only part of the entire operational path, namely measuring the ingest rate of the telemetry ingest path and the compute cost of the on-chain settlement instruction on a per-part basis, but has not yet measured the end-to-end latency from meter reading to on-chain confirmation, nor the order matching rate under multiple order-volume levels. As for the throughput of the settlement path, it was measured on a single validator (see @sec:onchain-throughput) but does not yet cover a multi-node permissioned network that includes consensus cost, and the batch settlement discussed at the design level has not yet been evaluated as an actual experiment. In terms of trust, the energy quantity and grid-stability conditions are enforced in the off-chain layer by the Aggregator Bridge and the oracle authority, whose collusion or compromise is not yet prevented by cryptographic mechanisms (see @sec:threat-model). Likewise, the security assumption of the consensus (PoH together with Tower BFT) under a permissioned network that governs participation via PoA is also an architectural assumption that has not yet been quantitatively evaluated under validators with deviant behavior.

== Threats to Validity
The measurement results in this work have three caveats in interpretation. First (internal validity), the workload in the ingest experiment was generated by a single sender client operating asynchronously, so the measured ingest rate is a lower bound that also reflects the sender-side limitation, not the true capacity ceiling of the ingest service (see @sec:ingest-saturation). Second (construct validity), the design rate of 5.33 readings per second is computed from the number of meters and the transmission cycle, not the maximum measured rate, so comparing the two figures must clearly state the context of each value. Third (external validity), the compute cost of the settlement instruction was measured on a single solana-test-validator version, and that value is a logical program cost (deterministic CU) independent of hardware, but the latency and throughput on a real production network may differ. All results should therefore be interpreted as an architectural evaluation on a simulated system.

== Future Work
Future work should develop the connection with real Smart Meters via the DLMS/COSEM standard and evaluate the entire operational path more completely, including measuring end-to-end latency and extending the settlement throughput measurement reported on a single validator in @sec:onchain-throughput to a multi-node permissioned network that includes consensus cost, together with open-loop measurement to find the TPS ceiling at the SLA level, and experimenting with batch settlement to confirm the reduction of compute cost per order pair, as well as measuring the ceiling of the ingest path with multiple parallel senders that separate the sender-side cost from the ingest service. In terms of trust, the residual trust of the off-chain layer should be reduced with multi-oracle attestation or cryptographic proof, and the consensus of the permissioned network (governing participation via PoA) should be quantitatively evaluated under nodes with deviant behavior. In addition, models for grid stability, islanding detection, and demand response should be added so that the safety evaluation of energy trading more closely approximates real usage. The next experiment should clearly define a reproducible workload, such as the number of meters, sampling interval, transaction mix, validator count, queue depth, failure/retry policy, and market-clearing output metrics.

Beyond the above, three quantitative evaluation directions are explicitly left open, namely:
- *Allocative efficiency / welfare:* measure the gains from trade of the CDA mechanism relative to a uniform-price clearing baseline and the feed-in tariff on real matching data from a full simulated workload, in order to confirm the economic premium analyzed at the model level in @sec:revenue-sensitivity with actual measurement instead of computation from fixed parameters.
- *Cost per trade:* convert the per-transaction compute cost into a fee in lamport units and baht at a given rate, then report the fee-to-trade-value ratio, which is a key deciding criterion for real-world adoption.
- *Liveness & baseline:* evaluate the availability of the permissioned network when some validator nodes fail (1-of-N down), and conduct a quantitative head-to-head comparison with other permissioned platforms, especially Hyperledger Fabric, on the same energy workload, in order to extend the qualitative comparison in @tbl:comparison into a directly comparable joint measurement.
