#heading(level: 1)[SETTLEMENT MODEL & INVARIANTS] <sec:settlement-model-invariants>

#heading(level: 2)[Solana Architecture]
ระบบนี้ออกแบบบนสถาปัตยกรรมของ Solana ซึ่งประมวลผล Smart Contract ผ่าน Solana Virtual Machine (SVM) @yakovenkoSolanaWhitepaper โดยใช้ Anchor Framework @anchorDocs เป็นชั้นกำหนดโครงสร้างของโปรแกรม ได้แก่ account validation, instruction handler และ Event log คุณสมบัติสำคัญที่นำมาใช้คือ Program Derived Address (PDA) สำหรับสร้างบัญชีที่ตรวจสอบ ownership ได้แบบ deterministic และ Sealevel parallel runtime สำหรับประมวลผลธุรกรรมที่ไม่ใช้ account เดียวกันแบบขนาน ทั้งนี้บทความนี้ไม่ใช่ผลวัดจากเครือข่าย Solana production แต่ใช้คุณสมบัติของ SVM และ PDA เป็นข้อกำหนดเชิงออกแบบสำหรับระบบจำลอง

#heading(level: 2)[Settlement Model]
แบบจำลองการชำระธุรกรรมของระบบแบ่งความรับผิดชอบออกเป็นสองชั้นอย่างชัดเจน ชั้นนอกเชน (off-chain) ประกอบด้วย Aggregator Bridge ซึ่งตรวจสอบลายเซ็น Ed25519 ของข้อมูลมาตรวัด ตรวจรูปแบบข้อมูลตามมาตรฐาน DLMS/COSEM และประเมินเงื่อนไขปริมาณพลังงานคงเหลือ (available surplus) และ Grid stability ร่วมกับ Trading Service ที่จับคู่คำสั่งซื้อขายด้วยอัลกอริทึม Continuous Double Auction (CDA) ส่วนชั้นบนเชน (on-chain) คือ Anchor program @anchorDocs ที่รับเฉพาะคู่คำสั่งที่ผ่านการตรวจสอบแล้ว และทำหน้าที่บันทึกการชำระธุรกรรมที่ตรวจสอบย้อนหลังได้ ก่อนบันทึก settlement โปรแกรมจะตรวจสอบ account ownership ลายเซ็น Ed25519 ของทั้งผู้ซื้อและผู้ขายบน order payload การกันส่งซ้ำผ่านบัญชี order nullifier และสถานะ escrow โดยเงื่อนไขปริมาณพลังงานและ oracle attestation ถูกบังคับใช้ในชั้น off-chain ก่อนการ submit มิได้ตรวจซ้ำบนเชน โครงสร้างบัญชีทั้งหมดใช้ Program Derived Address (PDA) เพื่อแยก state ของแต่ละธุรกรรมและตรวจสอบ ownership ได้แบบ deterministic รายละเอียดของโปรแกรมและบัญชี PDA อธิบายใน @sec:smart-contract-programs @solanaPdaDocs

#heading(level: 2)[Invariants]
จากแบบจำลองข้างต้น ระบบกำหนดเงื่อนไขความถูกต้อง (invariants) ที่ต้องคงไว้ดังนี้
- I1 (Replay-freedom): คู่คำสั่งที่จับคู่แล้วถูกชำระได้เพียงครั้งเดียว โดยบัญชี order nullifier บนเชนกันการส่งซ้ำของคำสั่งเดิม
- I2 (Settlement authorization): การชำระธุรกรรมต้องมีลายเซ็น Ed25519 ของทั้งผู้ซื้อและผู้ขายบน order payload จึงจะถูกบันทึก
- I3 (Surplus bound): ปริมาณพลังงานของคำสั่งขายต้องไม่เกินค่าพลังงานคงเหลือที่รับรอง (available surplus) ซึ่งบังคับใช้ในชั้น off-chain ก่อน submit
- I4 (Mint idempotency): การสร้าง energy token ผ่าน mint_generation ใช้คีย์ (meter_id, ช่วงเวลา settlement) จึงสร้างได้เพียงครั้งเดียวต่อหนึ่งหน้าต่างเวลา
- I5 (REC double-claim freedom): การออก Renewable Energy Certificate (REC) ถูกจำกัดด้วยปริมาณการผลิตที่ยังไม่ถูกอ้างสิทธิ์ (unclaimed generation) และตัดยอดผ่าน Cross-Program Invocation (CPI) ไปยังโปรแกรม registry
- I6 (Governance authorization): การเปลี่ยนแปลงนโยบายและการรับรอง REC ต้องลงนามโดยผู้มีสิทธิ์หลัก (PoA authority) ส่วนการลงคะแนน DAO ป้องกันการลงคะแนนซ้ำด้วยบัญชี vote record ต่อคู่ (proposal, voter)

เงื่อนไขเหล่านี้ถูกบังคับใช้จริงในโปรแกรมบนเชนที่อธิบายใน @sec:smart-contract-programs กล่าวคือ I1 และ I2 บังคับใช้ในคำสั่ง `settle_offchain_match` ของโปรแกรม trading ผ่านบัญชี order nullifier (seed `[nullifier, user, order_id]`) และการตรวจลายเซ็น Ed25519 ของผู้ซื้อและผู้ขายผ่าน instructions sysvar, I4 บังคับใช้ในคำสั่ง `mint_generation` ของโปรแกรม energy-token ที่ตรวจสถานะ `minted` ของบัญชี mint record ต่อคีย์ `(meter_id, window_start_ms)` ก่อนเรียก mint CPI, I5 บังคับใช้ในโปรแกรม governance ที่ตัดยอด `unclaimed_generation` แล้วเรียก CPI `mark_erc_claimed` ไปยังโปรแกรม registry และ I6 บังคับใช้ผ่านการจำกัดสิทธิ์ของผู้มีอำนาจ (admit/revoke aggregator และการโอนสิทธิ์แบบสองขั้นตอน) ร่วมกับบัญชี vote record (seed `[vote, proposal, voter]`) และเงื่อนไข quorum ขั้นต่ำ ส่วน I3 (surplus bound) เป็นเงื่อนไขที่บังคับใช้ในชั้น off-chain ตามการออกแบบ โดยบนเชนยังจำกัดปริมาณที่ชำระไม่ให้เกินส่วนที่เหลือของคำสั่งผ่านบัญชี nullifier

#heading(level: 2)[Consensus]
ระบบนี้ตั้งสมมติฐานเป็นเครือข่าย permissioned แบบ consortium โดยใช้แนวคิด Proof of Authority (PoA) @joshi2021poa เป็นชั้น governance และการควบคุมสิทธิ์การเข้าร่วม กล่าวคือ Validator Node และผู้เข้าร่วมเป็นหน่วยงานที่ได้รับอนุญาตตามนโยบาย governance ทั้งนี้ PoA ในบริบทนี้ไม่ใช่การปรับเปลี่ยนกลไกฉันทามติระดับ Layer 1 ของเครือข่าย Solana-compatible ซึ่งยังคงอาศัย Proof of History (PoH) ร่วมกับ Tower BFT ในการยืนยันธุรกรรมและประกาศสิ้นสุดบล็อก แต่เป็นสมมติฐานเชิงสถาปัตยกรรมด้านการกำกับดูแลและสิทธิ์ของเครือข่ายสำหรับระบบจำลอง
