= THE PAYMENT LEG: FIAT ON-RAMP, REDEMPTION, AND A DISCLOSED-INVARIANT REGISTRY <sec:thbc-payment-leg>

_The baht side of settlement, and a method for reporting what a design guarantees: a machine-readable invariant registry in which two of nine entries are published as unmet._

@sec:token-model treats THBC as an on-chain object — a six-decimal mint whose supply is bounded by an attested reserve. That account is only half of a settlement currency. A token referenced to the baht must also have a route by which baht enter and leave, and that route is irreducibly off-chain: a bank credit, a compliance screen, an attestation of what the reserve account holds, and, on the way out, a wire. This section describes that layer, and it does so through the artifact the layer is organized around, which is of more general interest than the layer itself.

== An Invariant Registry as the Unit of Claim

The payment service does not document its guarantees in prose. It enumerates them as nine numbered invariants — F1 through F9 — in a compiled data structure that is served live from an administrative endpoint, so that any operator, auditor, or reviewer reads the same statement the code compiles against. Each entry carries a formal statement, a status, an enforcement class, and, when the status is anything other than fully met, a mandatory description of the gap.

Two aspects of this construction do the work. The first is that status and enforcement are distinct axes. A property may be *enforced* — with a test that exercises the violating path, not merely a passing happy path — *partial*, *design-only*, or *violated*, which is strictly worse than design-only because code is known to contradict it. Orthogonally, enforcement is classified by the mechanism that provides it: the Solana runtime, an on-chain program check, an off-chain check, or nothing. The ordering of that second axis is the useful part, and it is discussed in @sec:enforcement-strength.

The second is that the registry is adversarial toward its own author. A non-enforced entry cannot compile without a gap string, so an invariant cannot be quietly downgraded; the accompanying test asserts the expected status of every entry, so a regression that weakens a guarantee fails the suite rather than passing silently under a softened claim. The registry as evaluated is reproduced in @tbl:invariants.

#figure(
  placement: top,
  scope: "parent",
  caption: [The F1–F9 registry as evaluated. Status and enforcement are independent axes; every non-enforced entry carries a disclosed gap.],
  text(size: 7.5pt)[
    #table(
    columns: (auto, auto, auto, auto, 1fr),
    inset: (x: 3.5pt, y: 3pt),
    align: (left + horizon, left + horizon, left + horizon, left + horizon, left + horizon),
    table.header([], [Invariant], [Status], [By], [Disclosed gap]),
    [F1], [Reserve sufficiency], [Enforced], [on-chain], [—],
    [F2], [Issuance conservation], [Partial], [off-chain], [detective, not preventive — no write is rejected for causing drift; a reconciler reports it afterwards],
    [F3], [Deposit idempotency], [Enforced], [runtime], [—],
    [F4], [Burn-before-wire], [Partial], [off-chain], [ordering is enforced by the redemption state machine, but no fiat rail exists to test the barrier against],
    [F5], [Attestation freshness], [Enforced], [on-chain], [—],
    [F6], [Backing-set purity], [Partial], [on-chain], [the code no longer mints against volatile collateral, but supply minted by the previous instruction is still outstanding and remains so backed],
    [F7], [Redemption liveness], [Enforced], [on-chain], [—],
    [F8], [Non-custody], [*Violated*], [—], [the platform provisions and stores every user's key under service-only secrets and signs settlement with a single platform key; custody is the chosen posture, not a drift],
    [F9], [Attestation independence], [Design-only], [—], [initialization never compares the attestor key to the parameter-admin key, and the evaluated deployment has them equal],
    )
  ],
) <tbl:invariants>

== Two Orderings Carry the Safety

Most of the payment layer is bookkeeping. Two orderings are not, and they are the reason the layer exists as a distinct service rather than as handlers on an existing one.

On the on-ramp, attestation must precede issuance. A deposit advances through observation, compliance screening, attestation, and only then issuance; the state machine offers no transition from the screened state directly to the issued state, which makes the dangerous interval — tokens issued against a reserve figure that has not yet been attested — unrepresentable rather than merely discouraged. The ceiling checked at that point is the attested reserve less the deposits known to be encumbered — fiat that has cleared the bank but backs no token, because it failed a compliance screen or is disputed. This is also the clearest instance of the registry driving work rather than merely describing it. The encumbrance figure originally had no on-chain field, so the service enforced the tighter ceiling from its own records while the program enforced the bare attested reserve; the service was therefore stricter than the chain, and that asymmetry was published as the F1 gap rather than presented as a safety margin, for the reason that made it a gap at all — a caller who bypassed the service got the looser ceiling. Closing it turned out to require less than the gap text assumed: the field is a 64-bit integer, not a public key, so it fits the tail of the treasury account's existing padding at an already-aligned offset, leaving the struct the same size and every deployed account still deserializable, with no re-initialization. Accounts written before the field existed read it as zero, so their ceiling is unchanged until an attestation reports an encumbrance. With the service now publishing the encumbered total on every attestation, both sides evaluate the same inequality and F1 moved from partial to enforced.

On the off-ramp, a confirmed burn must precede a fiat payout. The barrier is confirmation, not acceptance — a submission acknowledgement leaves the record in its requested state and does not start the recovery clock — and within the payout routine the record is persisted *before* the payout is enqueued. That ordering is chosen against the intuitive one on an explicitly asymmetric basis: if the process dies between the two steps, the surviving record claims a payout that may never have been sent, and an operator investigates. The reverse order loses the record of a wire that *was* sent, and a double payout is unrecoverable in a way that a double burn is not. The payout enqueue is idempotent on the pair of user and sequence number so that the resulting retry is safe.

== The Strength of an Enforcement Mechanism <sec:enforcement-strength>

The registry's enforcement axis encodes a ranking that the rest of this work applies informally and that is worth making explicit: a guarantee provided by the runtime is stronger than one provided by a program check, which is in turn stronger than one provided by an off-chain check.

F3, deposit idempotency, is the clearest case. The issuance instruction creates a nullifier account addressed by the hash of the bank reference, using the framework's `init` constraint, in the *same instruction* as the mint. A replayed bank webhook is therefore rejected by the Solana runtime at the account level, before any program code executes: no application bug can defeat it, and the mint and the nullifier either both occur or neither does. Splitting these across two transactions would not implement the invariant at all — it would implement a check with a window.

F7, redemption liveness, uses the same idea inverted. Redemption escrows the tokens without burning them, so they remain within the tracked supply and remain recoverable; a confirmation burns and a reclaim returns them after a fixed delay of 24 hours, frozen per record so that changing the parameter cannot extend an in-flight holder's wait. Both terminal instructions *close* the record, so a double confirmation, or a confirmation after a reclaim, fails at the account level rather than through a comparison the program might get wrong. A useful side effect is that the set of live escrow accounts *is* the pending queue, which makes its length derivable rather than a stored counter that can drift. Reclaim is deliberately not gated on the pause flag, on the principle that pausing the system must never trap a holder's tokens.

F5, attestation freshness, is an ordinary program check, and its two details are both about ordering. It is evaluated *before* the F1 ceiling, because comparing supply against a stale reserve figure is not conservative but meaningless; and a future-dated attestation is rejected outright rather than treated as maximally fresh, so that clock skew cannot be used to buy freshness.

F6 illustrates the remaining distinction, between a claim about code and a claim about state. The instruction that previously minted the settlement currency against volatile collateral was replaced by an inventory transfer out of a platform-held vault, at identical pricing, so that no program mints or burns the currency any longer and the invariant now holds by construction: the quote type has no field capable of expressing a supply change. The invariant nonetheless remains partial, because supply minted by the earlier instruction is still outstanding and still backed by the volatile asset. F6 is a statement about what backs the supply, and code alone cannot retire supply that already exists.

== Two Published Failures

The registry's value is easiest to see in the two entries it does not claim.

F8 asserts that no platform key appears in a signer set able to move user funds, and it is recorded as violated at the system level. The service itself is genuinely non-custodial — no method on any of its ports accepts a key, keypair, or signer, and its sweep of overdue redemptions deliberately *reports* them rather than reclaiming them, because reclaiming would require the holder's key. That is a property of one service and not of the platform. As described in @sec:identity-onboarding, the identity service generates each user's keypair and encrypts it under two service-configuration secrets with no user password in the derivation, so anyone holding those secrets and the database can sign as any user. Nor is this capability dormant: per-user signing was *removed* in favour of a single platform key held in the transaction-signing service, and the settlement entry point the evaluated deployment actually uses pools escrow in platform-owned accounts with the platform as sole signer (@sec:trading-program). Custody is therefore the direction the platform chose rather than a gap it drifted into, and the honest disposition of the invariant is to retire the non-custody claim rather than to describe it as forthcoming.

F9 asserts that the reserve attestor and the parameter administrator are distinct keys, and it is recorded as design-only after an earlier entry claimed it was enforced on-chain. The initialization instruction accepts an attestor argument and stores it without comparing it to the authority, and the program defines no error for the equality case; the evaluated deployment consequently runs with the two roles held by the same key. There is also a live reason it must currently be so, and the shape of that reason is instructive. Enforcing F9 takes three changes, and any one alone breaks the deployment: a distinct signing key for attestation; a relaxation of the transaction-signing service's authorization gate, which today rejects any key identifier other than the single platform key and is the reference monitor's own check rather than a configuration value; and a means of moving the attestor on an already-initialized treasury, since the field is written once and has no setter — and a setter gated on the parameter admin would partly defeat the invariant, since that admin could then grant itself attestation rights. Adding the equality check alone is worse than doing nothing: it would not touch the treasury already deployed, and it would make the initialization script fail in every fresh environment, because that script passes one key for both roles. The off-chain service does reject the equality, but that is the service declining to submit rather than the chain declining the transaction — advisory, and bypassed by any other caller.

Both entries point at the same place. The reserve figure is a single unsigned integer written by a single signer, and reserve sufficiency, attestation freshness, the peg claim, and the solvency of every user balance all reduce to that number being honest. Nothing in this design improves on that; an attestation that fails to cover supply is logged as an error, which makes a lie visible without preventing it. Collusion between the fiat custodian and the attestor is the single point of failure, and no mechanism here addresses it.

== Scope: What Is Modeled and What Is Built

The payment leg is a model executed against a simulator, and the code is arranged so that this cannot be mistaken. No fiat rail of any kind exists, and the compliance port refuses every screen outside simulated mode rather than defaulting to a pass. The adapter that talks to the real chain returns an `Unsupported` result — surfaced as `501 Not Implemented` — for issuance, redemption escrow, confirmation, reclaim, and state snapshot, and this is a deliberate refusal rather than unfinished work: routing issuance to the minting instruction that *does* exist would produce a service that appears to implement the on-ramp while violating backing-set purity on every deposit. `Unsupported` is a distinct outcome from `Rejected` precisely so that an operator can distinguish "not built" from "the chain said no". The snapshot call refuses for a subtler reason — three of the four fields it would return have no on-chain home, and synthesizing them would report a tighter reserve ceiling than the chain actually enforces. The service reports its posture at startup and on every response, so simulated state cannot be read as live.

Verification is correspondingly scoped. The off-chain layer carries 205 tests that run with no infrastructure at all, which is a direct consequence of the sync-core discipline of @sec:system-architecture: every invariant decision is a pure function over values, so the whole registry is exercisable without a database, a broker, or a validator. The on-chain half is pinned by 27 in-process SVM cases covering F1, F3, F5, F6, and F7 against the compiled program — including F3's replay revert, which is a property of the runtime's account initialization and can only be demonstrated on an SVM, and F5's freshness halt, which requires warping the cluster clock. That suite is mutation-checked three times: removing the freshness guard kills exactly the three cases that test it and nothing else, removing the redemption timelock kills exactly the boundary case, and removing the encumbrance subtraction from the reserve ceiling kills three of F1's four cases — so the suite demonstrably detects a regression rather than merely passing. Following the standard set in @sec:threat-model, we report this as evidence about the invariants named and not as coverage of the payment leg as a whole; the fiat halves of F2 and F4 have no rail to be tested against, and no test can establish F8 or F9, which the registry reports as unmet rather than untested.
