This whitepaper introduces GridTokenX, a Decentralized Physical Infrastructure Network (DePIN) @depin purpose-built for real-time, peer-to-peer energy trading in distributed power grids. The global proliferation of rooftop solar installations, battery energy storage systems (BESS), and electric vehicle (EV) chargers has created millions of prosumers — participants who simultaneously produce and consume electricity — yet existing grid management infrastructure remains fundamentally centralized, opaque, and ill-suited to coordinate this distributed flexibility at scale.

GridTokenX addresses this structural gap by constructing a vertically integrated technology stack that spans from physical hardware to on-chain settlement. At the edge, industrial-grade IoT gateways translate raw meter telemetry from DLMS/COSEM and OCPP 2.0.1 protocols into cryptographically signed data payloads. These payloads traverse a mutual TLS (mTLS) secured service mesh, are validated by an Oracle Bridge microservice, and are ultimately committed to the Solana blockchain @solana2021 via Anchor-based smart contracts @anchor — achieving end-to-end latency well below one second.

The platform's economic model is anchored by a triple-token architecture: *GRID*, a 1:1 kWh-pegged energy token minted upon verified renewable generation; *GRX*, a utility and governance token used for staking, fee payment, and protocol voting; and *gTHB*, a reserve-backed stablecoin pegged to the Thai Baht for stable, fiat-denominated settlement. A Continuous Double Auction (CDA) matching engine, implemented both off-chain for low-latency order matching and on-chain for trustless settlement, enables prosumers to trade energy at market-determined prices with atomic finality.

Grid stability is preserved through a zone-aware congestion management layer that enforces dynamic wheeling charges, Virtual Power Plant (VPP) capacity limits, and Grid Loss Factor (GLF) adjustments at the smart contract level. Identity and access are governed by a KYC-integrated IAM service with Role-Based Access Control (RBAC), while Renewable Energy Certificate (REC) issuance is automated and tamper-proof via on-chain validator co-signatures.

Security is enforced through a defense-in-depth strategy encompassing Ed25519 hardware signing at the edge, cross-instruction signature verification on Solana, nullifier-based replay protection, and Hardware Security Module (HSM)-backed multisig for stablecoin issuance. Empirical benchmarks demonstrate that the sharded on-chain architecture sustains throughput exceeding 50,000 settlement operations per hour while remaining within Solana's per-transaction compute unit limits.

GridTokenX is designed as an open, composable protocol. Its modular architecture enables future extension to other utility markets — including water distribution, broadband bandwidth trading, and carbon credit settlement — positioning it as foundational infrastructure for the tokenized physical economy.
