apiVersion: v1
kind: Namespace
metadata:
  name: gridtokenx
  labels:
    name: gridtokenx
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: gridtokenx-infra
  labels:
    name: gridtokenx-infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: gridtokenx-observability
  labels:
    name: gridtokenx-observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: gridtokenx-prod
  labels:
    name: gridtokenx-prod
    istio-injection: enabled
