"""Suite 50 — Chain Bridge previously-uncovered gRPC reads + the read-only
NATS `chain.tx.status` subject.

Complements `test_chain_bridge.py` (GetSlot/GetLatestBlockhash/GetBalance) and
`test_nats_tx.py` (submit/simulate write path). Here we exercise the read RPCs
that had no E2E coverage:

  - GetAccountData            (service.rs:499)
  - GetTokenAccountBalance    (service.rs:617)
  - GetRecentPrioritizationFees (service.rs:576)
  - GetEpochInfo              (service.rs:807)
  - GetSignatureStatus        (service.rs:655)
  - RequestAirdrop            (service.rs:732)  -- local validator only

…and the read-only NATS subject:

  - chain.tx.status           (consumer.rs:836 -> reply chain.tx.statusresult.{cid})

All proto method names + field casing verified against
`gridtokenx-blockchain-core/proto/chain_bridge.proto`. ConnectRPC/JSON renders
proto field names in lowerCamelCase, so request/response keys are camelCase
(e.g. `accountKeys`, `uiAmount`, `lastValidBlockHeight`); NATS envelope/result
JSON uses serde snake_case (matching `nats_schema.rs` and `test_nats_tx.py`).

Run: cd tests/e2e && uv run --no-project python -m pytest 50_chain_bridge/test_chain_reads.py -v
Skips gracefully if Chain Bridge / NATS / validator are unreachable, or for the
mainnet-only RequestAirdrop case.
"""
import os
import time
import uuid
from pathlib import Path

import pytest
import requests

GRPC = os.getenv("CHAIN_BRIDGE_GRPC", "localhost:5040")
SVC = "gridtokenx.chain.v1.ChainBridgeService"
ADMIN_ROLE = {"x-gridtokenx-role": "admin"}

# 11111… = the System program; exists on any cluster (proto GetAccountDataRequest.pubkey).
SYSTEM_PROGRAM = "11111111111111111111111111111111"

# Dev mTLS material generated by `just gen-certs` (mirrors test_chain_bridge.py).
ROOT = Path(__file__).resolve().parents[3]
CERT_DIR = ROOT / "infra" / "certs"
CA = CERT_DIR / "ca.crt"
CLIENTS = CERT_DIR / "clients"
# mTLS is active only when certs exist AND the bridge is not insecure — the dev stack
# ships certs but runs insecure HTTP (CHAIN_BRIDGE_INSECURE=true), so certs-on-disk alone
# must not force https (which would skip the whole suite against an http bridge).
MTLS = (
    CA.is_file()
    and (CLIENTS / "admin.crt").is_file()
    and os.getenv("CHAIN_BRIDGE_INSECURE", "").lower() != "true"
)

BASE = os.getenv("CHAIN_BRIDGE_HTTP", f"{'https' if MTLS else 'http'}://{GRPC}")

# meter-service is the only non-Admin role permitted to query chain.tx.status
# (consumer.rs:873). Its SPIFFE URI maps to ServiceRole::MeterService
# (gridtokenx-blockchain-core/src/auth.rs:137).
STATUS_IDENTITY = "spiffe://gridtokenx.th/prod/meter-service"


def _client_cert(name: str):
    return (str(CLIENTS / f"{name}.crt"), str(CLIENTS / f"{name}.key"))


def connect_call(method: str, body: dict, headers: dict = None,
                 timeout: float = 8.0, identity: str = "admin"):
    """Connect unary call -> (status_code, json|text). Same shape as
    test_chain_bridge.connect_call so both auth modes work."""
    h = {"Content-Type": "application/json"}
    if headers:
        h.update(headers)
    kwargs = {"json": body, "headers": h, "timeout": timeout}
    if MTLS:
        kwargs["verify"] = str(CA)
        if identity is not None:
            kwargs["cert"] = _client_cert(identity)
    r = requests.post(f"{BASE}/{SVC}/{method}", **kwargs)
    try:
        return r.status_code, r.json()
    except ValueError:
        return r.status_code, r.text


def _reachable() -> bool:
    try:
        connect_call("GetSlot", {}, ADMIN_ROLE, timeout=4)
        return True
    except requests.RequestException:
        return False


pytestmark = pytest.mark.skipif(
    not _reachable(),
    reason="Chain Bridge unreachable (down, or mTLS-only without infra/certs — "
           "run `just gen-certs`, or start with CHAIN_BRIDGE_INSECURE=true).",
)


def _authorized() -> bool:
    code, _ = connect_call("GetSlot", {}, ADMIN_ROLE)
    return code == 200


# --- gRPC read RPCs -------------------------------------------------------

def test_get_account_data_system_program():
    """GetAccountData for an existing account: exists=true, data present.
    Response fields: exists, data (proto GetAccountDataResponse, service.rs:524)."""
    if not _authorized():
        pytest.skip("server rejects admin identity; auth mode mismatch")
    code, body = connect_call("GetAccountData", {"pubkey": SYSTEM_PROGRAM}, ADMIN_ROLE)
    assert code == 200, f"GetAccountData failed: {code} {body}"
    # System program is an executable account -> exists must be true.
    assert body.get("exists") is True, f"system program not found: {body}"


def test_get_account_data_nonexistent_account():
    """GetAccountData for a never-funded account: exists=false (service.rs:532).
    Use a deterministic but unfunded pubkey (all 2s = address '111…2' family is
    unlikely funded on a fresh local validator)."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    # A valid base58 pubkey that is essentially never an existing account.
    never = "GTKxoNeXiStentAccountForE2eTestNeverFunded11"
    code, body = connect_call("GetAccountData", {"pubkey": never}, ADMIN_ROLE)
    # Either a structured invalid-pubkey error, or a 200 with exists=false.
    # ConnectRPC omits default (false) bools, so a missing `exists` == false.
    if code == 200:
        assert body.get("exists", False) is False, f"unexpected existing account: {body}"
    else:
        assert code != 200
        if isinstance(body, dict):
            assert body.get("code") or body.get("message"), f"unstructured error: {body}"


def test_get_account_data_invalid_pubkey_structured_error():
    """Malformed pubkey -> structured InvalidArgument, not a silent 200
    (service.rs:519-520)."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    code, body = connect_call("GetAccountData", {"pubkey": "not-a-pubkey"}, ADMIN_ROLE)
    assert code != 200, f"invalid pubkey accepted: {code} {body}"
    if isinstance(body, dict):
        assert body.get("code") or body.get("message"), f"unstructured error: {body}"


def test_get_token_account_balance_invalid_pubkey_structured_error():
    """GetTokenAccountBalance on a malformed pubkey -> structured error
    (service.rs:637). We assert the error shape rather than requiring a live
    token account to exist (no prior state needed). Response fields on success:
    amount, decimals, uiAmount (proto GetTokenAccountBalanceResponse)."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    code, body = connect_call("GetTokenAccountBalance",
                              {"pubkey": "not-a-pubkey"}, ADMIN_ROLE)
    assert code != 200, f"invalid pubkey accepted: {code} {body}"
    if isinstance(body, dict):
        assert body.get("code") or body.get("message"), f"unstructured error: {body}"


def test_get_token_account_balance_non_token_account():
    """GetTokenAccountBalance on the System program (a valid pubkey that is NOT
    an SPL token account): the RPC must not return a silent success — either a
    structured error or a zeroed balance. Exercises the success-decode path
    fields (amount/decimals/uiAmount, service.rs:643-645) without prior state."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    code, body = connect_call("GetTokenAccountBalance",
                              {"pubkey": SYSTEM_PROGRAM}, ADMIN_ROLE)
    if code == 200:
        # If the bridge maps it to a default balance, fields must still be the
        # documented shape and amount must be parseable.
        assert "amount" in body, f"missing amount: {body}"
        int(body["amount"])
    else:
        assert code != 200
        if isinstance(body, dict):
            assert body.get("code") or body.get("message"), f"unstructured error: {body}"


def test_get_recent_prioritization_fees_empty_accounts():
    """GetRecentPrioritizationFees with no account keys -> a fees array
    (possibly empty). Request field: accountKeys (repeated string). Response:
    fees[] each {slot, prioritizationFee} (proto PrioritizationFee,
    service.rs:602-607). Needs no prior state."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    code, body = connect_call("GetRecentPrioritizationFees",
                              {"accountKeys": []}, ADMIN_ROLE)
    assert code == 200, f"GetRecentPrioritizationFees failed: {code} {body}"
    # Connect omits empty repeated fields, so `fees` may be absent or [].
    fees = body.get("fees", [])
    assert isinstance(fees, list), f"fees not a list: {body}"
    for f in fees:
        # Each entry must carry the documented numeric fields when present.
        assert "slot" in f or "prioritizationFee" in f, f"bad fee entry: {f}"


def test_get_recent_prioritization_fees_with_account():
    """Same RPC, scoped to the System program account key — exercises the
    pubkey-parse path (service.rs:595-597)."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    code, body = connect_call("GetRecentPrioritizationFees",
                              {"accountKeys": [SYSTEM_PROGRAM]}, ADMIN_ROLE)
    assert code == 200, f"GetRecentPrioritizationFees failed: {code} {body}"
    assert isinstance(body.get("fees", []), list), f"fees not a list: {body}"


def test_get_epoch_info():
    """GetEpochInfo -> {epoch, slot} (proto GetEpochInfoResponse,
    service.rs:828-829). Needs no prior state; epoch>=0, slot>0 on a live chain."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    code, body = connect_call("GetEpochInfo", {}, ADMIN_ROLE)
    assert code == 200, f"GetEpochInfo failed: {code} {body}"
    # ConnectRPC omits zero-valued uint64 fields, so on a fresh validator `epoch`
    # (== 0) is absent. Slot is the always-present liveness signal here.
    assert "slot" in body, f"no slot in response: {body}"
    assert int(body["slot"]) > 0, f"invalid slot: {body}"
    int(body.get("epoch", 0))  # parses when present (>0 on a longer-lived chain)


def test_get_signature_status_unknown_signature_not_found():
    """GetSignatureStatus for a syntactically-valid but never-submitted signature
    must return the structured 'NotFound' shape (service.rs:687-690): confirmed
    false, status 'NotFound'. Avoids needing a real prior tx. Request field:
    signature; response fields: confirmed, status, error."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    # A valid 64-byte all-zero Ed25519 signature in base58 (parses, never landed).
    zero_sig = "1" * 64  # base58 '1' == zero byte; 64 chars -> 64 zero bytes
    code, body = connect_call("GetSignatureStatus", {"signature": zero_sig}, ADMIN_ROLE)
    assert code == 200, f"GetSignatureStatus failed: {code} {body}"
    # Connect omits default false/empty; the not-found branch sets status NotFound
    # and leaves confirmed at its default (false -> omitted).
    assert body.get("status") == "NotFound", f"expected NotFound, got: {body}"
    assert body.get("confirmed", False) is False, f"unexpectedly confirmed: {body}"


def test_get_signature_status_invalid_signature_structured_error():
    """GetSignatureStatus with a malformed signature -> structured InvalidArgument
    (service.rs:675-676), not a silent 200."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    code, body = connect_call("GetSignatureStatus",
                              {"signature": "not-a-signature"}, ADMIN_ROLE)
    assert code != 200, f"invalid signature accepted: {code} {body}"
    if isinstance(body, dict):
        assert body.get("code") or body.get("message"), f"unstructured error: {body}"


def test_request_airdrop_local_validator():
    """RequestAirdrop -> {success, signature} (proto RequestAirdropResponse,
    service.rs:748-750). Only works against a local/test validator; mainnet RPC
    rejects airdrops. Request fields: pubkey, lamports. Restricted to Admin /
    IamService (service.rs:738)."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    code, body = connect_call(
        "RequestAirdrop",
        {"pubkey": SYSTEM_PROGRAM, "lamports": 1000},
        ADMIN_ROLE,
        timeout=20.0,
    )
    if code != 200:
        # Mainnet / non-airdrop cluster: the validator rejects -> Internal error.
        # Treat as a not-applicable environment rather than a failure.
        pytest.skip(f"airdrop not available on this cluster (mainnet-only?): {code} {body}")
    assert body.get("success") is True, f"airdrop not success: {body}"
    assert body.get("signature"), f"no signature in airdrop result: {body}"


# --- NATS read-only subject: chain.tx.status ------------------------------

def test_nats_status_unknown_signature_not_found():
    """chain.tx.status for an unknown signature -> reply on
    chain.tx.statusresult.{cid} with found=false, status 'NotFound'
    (consumer.rs:836; reply subject per nats_schema.rs:123). Dev accepts an
    unsigned envelope (CHAIN_BRIDGE_REQUIRE_SIGNED_NATS=false); RBAC requires a
    meter-service / Admin identity (consumer.rs:873). Envelope JSON is serde
    snake_case (TxStatusMessage, nats_schema.rs:122)."""
    import nats_util  # provided on sys.path via conftest.py

    if not nats_util.reachable():
        pytest.skip("NATS bus unreachable")

    cid = str(uuid.uuid4())
    reply = f"chain.tx.statusresult.{cid}"
    # A valid base58 64-byte signature that was never submitted.
    zero_sig = "1" * 64
    envelope = {
        "correlation_id": cid,
        "reply_subject": reply,
        "signature": zero_sig,
        "service_identity": STATUS_IDENTITY,
        "created_at_ms": int(time.time() * 1000),
        # auth omitted -> unsigned; accepted in dev (log-only).
    }

    result = nats_util.request_reply_sync(
        "chain.tx.status", reply, envelope, timeout=20.0
    )

    # TxStatusResultMessage (nats_schema.rs:141): correlation_id, found, confirmed,
    # status, slot, error.
    assert result.get("correlation_id") == cid, f"correlation mismatch: {result}"
    assert result.get("found") is False, f"unexpectedly found unknown sig: {result}"
    assert result.get("status") == "NotFound", f"expected NotFound: {result}"
    assert result.get("confirmed") is False, f"unexpectedly confirmed: {result}"
