"""Suite 50 — Chain Bridge gRPC reads (ConnectRPC) + auth isolation.

Chain Bridge exposes ConnectRPC (gridtokenx.chain.v1.ChainBridgeService) — callable
over plain HTTP POST + JSON (Connect protocol), so no proto codegen needed here.

Two server modes, auto-detected:
- mTLS (default since `just gen-certs`): tests call https:// with per-SPIFFE-identity
  client certs from infra/certs/clients/, verifying the server against the dev CA.
- Insecure/header-auth dev mode: plain http:// with the x-gridtokenx-role header
  (CHAIN_BRIDGE_INSECURE=true grants Admin; CHAIN_BRIDGE_ALLOW_HEADER_AUTH=1 trusts
  the header). If neither mode is reachable, the suite skips.

NATS write path (chain.tx.submit) is exercised indirectly via IAM onboard
(suite 10) and settlement (suite 30); RBAC policy is covered by the Rust invariants
test wrapped in run.sh. This suite focuses on read correctness + role enforcement.

Run: cd tests/e2e && python -m pytest 50_chain_bridge -v
"""
import os
from pathlib import Path

import pytest
import requests

GRPC = os.getenv("CHAIN_BRIDGE_GRPC", "localhost:5040")
SVC = "gridtokenx.chain.v1.ChainBridgeService"
ADMIN_ROLE = {"x-gridtokenx-role": "admin"}

SYSTEM_PROGRAM = "11111111111111111111111111111111"  # exists on any cluster

# Dev mTLS material generated by `just gen-certs` (scripts/gen-certs.sh)
ROOT = Path(__file__).resolve().parents[3]
CERT_DIR = ROOT / "infra" / "certs"
CA = CERT_DIR / "ca.crt"
CLIENTS = CERT_DIR / "clients"
# Certs on disk alone don't mean the bridge is in mTLS mode — the dev stack ships
# certs (gen-certs) yet runs insecure HTTP (CHAIN_BRIDGE_INSECURE=true). Treat mTLS as
# active only when certs exist AND the bridge is NOT insecure; otherwise use plain HTTP
# (reads run; the mTLS-only isolation cases skip via their `not MTLS` guards).
MTLS = (
    CA.is_file()
    and (CLIENTS / "admin.crt").is_file()
    and os.getenv("CHAIN_BRIDGE_INSECURE", "").lower() != "true"
)

BASE = os.getenv(
    "CHAIN_BRIDGE_HTTP", f"{'https' if MTLS else 'http'}://{GRPC}"
)


def _client_cert(name: str):
    return (str(CLIENTS / f"{name}.crt"), str(CLIENTS / f"{name}.key"))


def connect_call(
    method: str,
    body: dict,
    headers: dict = None,
    timeout: float = 8.0,
    identity: str = "admin",
):
    """Connect unary call. Returns (status_code, json|text).

    In mTLS mode, `identity` picks the client cert (a name under
    infra/certs/clients/); pass identity=None to connect with no client cert.
    In plain-HTTP mode, identity is ignored — use the role header instead.
    """
    h = {"Content-Type": "application/json"}
    if headers:
        h.update(headers)
    kwargs = {"json": body, "headers": h, "timeout": timeout}
    if MTLS:
        kwargs["verify"] = str(CA)
        if identity is not None:
            kwargs["cert"] = _client_cert(identity)
    r = requests.post(f"{BASE}/{SVC}/{method}", **kwargs)
    try:
        return r.status_code, r.json()
    except ValueError:
        return r.status_code, r.text


def _reachable() -> bool:
    try:
        connect_call("GetSlot", {}, ADMIN_ROLE, timeout=4)
        return True
    except requests.RequestException:
        return False


pytestmark = pytest.mark.skipif(
    not _reachable(),
    reason="Chain Bridge unreachable (down, or mTLS-only without infra/certs — "
           "run `just gen-certs`, or start with CHAIN_BRIDGE_INSECURE=true).",
)


def _authorized() -> bool:
    """True if a read as admin (cert or header) returns 200."""
    code, _ = connect_call("GetSlot", {}, ADMIN_ROLE)
    return code == 200


# --- Read correctness ----------------------------------------------------

def test_get_slot_liveness():
    """Case 1: GetSlot returns a slot — Chain Bridge -> validator link alive."""
    if not _authorized():
        pytest.skip("server rejects admin identity; auth mode mismatch")
    code, body = connect_call("GetSlot", {}, ADMIN_ROLE)
    assert code == 200, f"GetSlot failed: {code} {body}"
    assert "slot" in body and int(body["slot"]) > 0, f"invalid slot: {body}"


def test_get_latest_blockhash():
    """Case 2: GetLatestBlockhash returns a non-empty blockhash."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    code, body = connect_call("GetLatestBlockhash", {}, ADMIN_ROLE)
    assert code == 200, f"GetLatestBlockhash failed: {code} {body}"
    assert body.get("blockhash"), f"empty blockhash: {body}"


def test_get_balance_system_program():
    """Case 3: GetBalance returns lamports for an existing account."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    code, body = connect_call("GetBalance", {"pubkey": SYSTEM_PROGRAM}, ADMIN_ROLE)
    assert code == 200, f"GetBalance failed: {code} {body}"
    # Connect JSON maps uint64 -> string or number; accept both.
    assert "lamports" in body, f"no lamports in response: {body}"
    int(body["lamports"])  # parses


def test_get_balance_invalid_pubkey_structured_error():
    """Case 4: malformed pubkey yields a structured error, not a silent 200."""
    if not _authorized():
        pytest.skip("auth mode mismatch")
    code, body = connect_call("GetBalance", {"pubkey": "not-a-valid-pubkey"}, ADMIN_ROLE)
    assert code != 200, f"invalid pubkey accepted: {code} {body}"
    if isinstance(body, dict):
        assert body.get("code") or body.get("message"), f"unstructured error: {body}"


# --- Auth isolation (header-auth dev mode) --------------------------------

def test_no_role_rejected():
    """Case 5: read without any role is denied (header-auth mode only)."""
    if MTLS:
        pytest.skip("mTLS mode: no-credential rejection covered by case 7")
    # CHAIN_BRIDGE_INSECURE grants Admin to everyone -> isolation not testable here.
    if os.getenv("CHAIN_BRIDGE_INSECURE", "").lower() == "true":
        pytest.skip("CHAIN_BRIDGE_INSECURE=true: all callers are Admin")
    code, body = connect_call("GetSlot", {})  # no role header
    assert code in (401, 403), f"unauthenticated read not denied: {code} {body}"


def test_unknown_role_rejected():
    """Case 6: an unrecognized role string is denied (header-auth mode only)."""
    if MTLS:
        pytest.skip("mTLS mode: identity comes from the client cert, not headers")
    if os.getenv("CHAIN_BRIDGE_INSECURE", "").lower() == "true":
        pytest.skip("CHAIN_BRIDGE_INSECURE=true: all callers are Admin")
    code, body = connect_call("GetSlot", {}, {"x-gridtokenx-role": "bogus-role"})
    assert code in (401, 403), f"bogus role not denied: {code} {body}"


# --- Auth isolation (mTLS mode) --------------------------------------------

def test_mtls_no_cert_rejected():
    """Case 7: connection without a client cert fails the mTLS handshake."""
    if not MTLS:
        pytest.skip("server not in mTLS mode")
    with pytest.raises(requests.exceptions.RequestException):
        connect_call("GetSlot", {}, identity=None)


def test_mtls_spiffe_role_mapping():
    """Case 8: SPIFFE identity in the client cert drives RBAC — reporting-service
    (read-only role) can read but is denied transaction submission."""
    if not MTLS:
        pytest.skip("server not in mTLS mode")
    code, body = connect_call("GetSlot", {}, identity="reporting-service")
    assert code == 200, f"reporting-service read denied: {code} {body}"

    code, body = connect_call(
        "SubmitTransaction",
        {"serializedTransaction": "", "keyId": "platform_admin"},
        identity="reporting-service",
    )
    assert code in (401, 403), f"reporting-service submit not denied: {code} {body}"
